FROM nvcr.io/nvidia/l4t-ml:r32.4.4-py3

RUN git clone -b 'v19.21' --single-branch https://github.com/davisking/dlib.git
RUN mkdir -p /dlib/build

RUN cmake -H/dlib -B/dlib/build -DDLIB_USE_CUDA=1 -DUSE_AVX_INSTRUCTIONS=1
RUN cmake --build /dlib/build

RUN cd /dlib; python3 /dlib/setup.py install

COPY . /root/face_recognition
RUN cd /root/face_recognition && \
    pip3 install -r requirements.txt

CMD cd /root/face_recognition/src && \
    python3 face_recognition_svm_predict.py