version: "3.8"

services:
  face_reco:
    image: face_reco
    command: ["python3", "face_recognition_svm_predict_sqs.py"]
    restart: always
    env_file: /root/env/aws.env
    volumes:
      - "/home/hogesako/poc_face_recognition/work/:/root/work"
