FROM nvcr.io/nvidia/l4t-ml:r32.4.4-py3

RUN set -x && \
    git clone -b 'v19.21' --single-branch https://github.com/davisking/dlib.git && \
    cd /dlib; python3 /dlib/setup.py install

COPY . /root/face_recognition
RUN cd /root/face_recognition && \
    pip3 install -r requirements.txt

WORKDIR /root/face_recognition/src

CMD cd /root/face_recognition/src && \
    python3 face_recognition_svm_predict.py